
name: "FitoxsAI/CodeQL"

on:
  push:
    branches: [ "main" ]

jobs:
  analyze:
    name: Scan with CodeQL
    runs-on: 'ubuntu-latest'
    timeout-minutes: 360
    permissions:
      pull-requests: write
      statuses: write
      contents: read
      actions: read      

    strategy:
      fail-fast: false
      matrix:
        language: ["python"]
        # CodeQL supports [ 'c-cpp', 'csharp', 'go', 'java-kotlin', 'javascript-typescript', 'python', 'ruby', 'swift' ]
        codeql_output_filename: ["app.sarif"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: ${{ matrix.language }}

      - name: Perform CodeQL analysis
        uses: github/codeql-action/analyze@v2
        with:
          category: "/language:${{ matrix.language }}"
          output: results

      - name: Show
        run: cat results/${{ matrix.codeql_output_filename }} 